### ISSUE TITLE
Using dataloader with juniper (again)

### ISSUE THREAD

**Issue by acelot** [cksac/dataloader-rs#18]
I have returned to my abandoned GraphQL project :) I'm trying to solve N+1 problem using `dataloader-rs` along with `juniper` and `actix-web`. I have two simple entities: `Article` and `Author`. One article have many authors. Below I will show the most important places of my program.

**Actix handler:**
```rust
use crate::graphql::context::Context;
use crate::graphql::schema::{create_schema, Schema};
use actix_web::{web, Error, HttpResponse};
use juniper::hProblemttp::GraphQLRequest;
use std::sync::Arc;

async fn graphql(
    ctx: web::Data<Context>,
    schema: web::Data<Arc<Schema>>,
    req: web::Json<GraphQLRequest>,
) -> Result<HttpResponse, Error> {
    let response = req.execute(&schema, &ctx).await;
    let json = serde_json::to_string(&response)?;
    Ok(HttpResponse::Ok()
        .content_type("application/json")
        .body(json))
}
```

**Authors dataloader:**
```rust
use crate::environment::db::Database;
use crate::models::author::Author;
use dataloader::BatchFn;
use std::collections::HashMap;
use tokio_postgres::Row;

pub struct AuthorsLoader {
    pub db: Database,
}

#[async_trait::async_trait]
impl BatchFn<i32, Author> for AuthorsLoader {
    async fn load(&self, keys: &[i32]) -> HashMap<i32, Author> {
        let client = self.db.get_client().await.unwrap();

        let map: HashMap<i32, Author> = client
            .query(
                "SELECT * FROM articles.authors WHERE id = ANY($1)",
                &[&keys.to_vec()],
            )
            .await
            .unwrap()
            .into_iter()
            .map(|r: Row| (r.get("id"), Author::from(r)))
            .into_iter()
            .collect();

        map
    }
}
```

**Article type resolver:**
```rust
use crate::{graphql::context::Context, models::{author::Author, article::Article}};
use itertools::Itertools;

#[juniper::graphql_object(Context = Context)]
impl Article {
    fn id(&self) -> &i32 {
        &self.id
    }

    fn title(&self) -> &str {
        &self.title
    }

    async fn authors(&self, ctx: &Context) -> Vec<Author> {
        let a = ctx.authors_loader
            .load_many(self.author_ids.clone())
            .await
            .values()
            .cloned()
            .collect_vec();

        a
    }
}
```

**Deps:**
```toml
[dependencies]
log = "0.4"
chrono = "0.4"
actix-web = "2.0"
actix-rt = "1.0"
env_logger = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
juniper = { git = "https://github.com/graphql-rust/juniper" }
dotenv = "0.15"
tokio = "0.2"
tokio-postgres = "0.5"
dataloader = "0.12"
futures = "0.3"
async-trait = "0.1"
itertools = "0.9"
```

## Problem

The panic occurs when the server tries to load authors through `load_many` method:
```
thread 'actix-rt:worker:0' panicked at 'found key 0 in load result', <::std::macros::panic macros>:5:6
```

*What I'm doing wrong?*
